### ISSUE TITLE
Pantalla Compra Mercadería

### ISSUE THREAD

**Issue by carlomagno83** [carlomagno83/souko#1]
- Cabecera(Proveedor, local, fecha, etc)
- Filtros sobre los productos(marca, tipo,modelo, etc)
- Grilla de mercaderia agregada.
- Grabar data, con ORM y transacciones.
- Ajustes del layout y login

**Comment by ghost** [comment]
Agregar funcionalidad ajax para carrito de compras.
mantener la tabla tallas reemplazando id con las tallas reales.

**Comment by Jorgeandom** [comment]
Agregar Precio de compra en formulario de ingreso de mercaderias
configurar las transacciones
Filtros no funciona en determinados casos por ejemplo al escoger marca y color, o tipo y color, o color y material y rango

**Comment by ghost** [comment]
En mi base de datos, falta la columna id a la tabla movimientos.
la lógica de producto, mercaderia y movimiento es:
producto ( tiene varias )-> mercaderias
mercaderias (tiene varios)-> movimientos  

producto #1 = zapatos cuero negro talla 38
en mercaderias
mercaderia #1 : producto #1
mercaderia #2 : producto #1
mercaderia #3 : producto #1
en movimientos

movimiento #1 : documento 1, ingreso, con fecha dd/mm,  mercaderia #1 
movimiento #5 : documento 2, salida a pto venta, con fecha dd/mm,  mercaderia #1 
movimiento #10 : documento 3, venta, con fecha dd/mm,  mercaderia #1 

aparte esta documento
documento (tiene varios) movimientos

**Comment by carlomagno83** [comment]
Augusto la tabla movimientos no necesita id pq el primary es compuesto( por las columnas mercaderia_id y documento_id ), las relaciones que haz puesto ahi puedes corroborarlas con el workbench,  yo veo justamente lo que pones ahi, me confirman.

@Jorgeandom  @augustomiyagi

**Comment by carlomagno83** [comment]
Aqui el modelo de la misma base de datos que tenemos.

![modelo](https://cloud.githubusercontent.com/assets/5098548/8312856/c7ee8484-19a4-11e5-8810-b8116fee6fd8.png)

**Comment by ghost** [comment]
La tabla movimientos ademas de contener la trazabilidad de cada mercadería, es como una tabla detalle para varios documentos y sirve para mostrar el orden del registro, por ejemplo, si se ingresa 5 códigos de mercaderías, en este orden 123, 89, 12, 1233, 540, cuando se muestre la guía habría que ordenarlo por fecha de actualización o creación, porque si se usa el código de mercadería, saldría como 12, 89, 123, 540 y 1233.
En este caso el id funciona como item de una tabla detalle, solo que al momento de mostrarlo en pantalla o reporte, se tiene que hacer un artificio.
